CREATE DATABASE BV_FINANCEIRA;

CREATE TABLE CLIENTES (
    CD_CLIENTE INT AUTO_INCREMENT,
    NM_CLIENTE VARCHAR(255) NOT NULL,
    PRIMARY KEY (CD_CLIENTE)
);

CREATE TABLE TRANSACOES (
    CD_CLIENTE INT,
    DT_TRANSACAO DATE,
    CD_TRANSACAO VARCHAR(255) NOT NULL,
    VR_TRANSACAO DECIMAL(10, 2),
    FOREIGN KEY (CD_CLIENTE) REFERENCES CLIENTES(CD_CLIENTE)
);

INSERT INTO CLIENTES (CD_CLIENTE, NM_CLIENTE)
VALUES
    (1, 'João'),
    (2, 'Maria'),
    (3, 'José'),
    (4, 'Adilson'),
    (5, 'Cleber');
    
INSERT INTO TRANSACOES (CD_CLIENTE, DT_TRANSACAO, CD_TRANSACAO, VR_TRANSACAO)
VALUES
    (1, '2021-08-28', 'CASHBACK', 20.00),
    (1, '2021-09-09', 'CASHIN', 78.90),
    (1, '2021-09-17', 'CASHOUT', 58.00),
    (1, '2021-11-15', 'CASHIN', 178.90),
    (1, '2021-12-24', 'CASHOUT', 110.37),
    (5, '2021-10-28', 'CASHIN', 220.00),
    (5, '2021-11-07', 'CASHIN', 380.00),
    (5, '2021-12-05', 'CASHOUT', 398.86),
    (5, '2021-12-14', 'CASHOUT', 33.90),
    (5, '2021-12-21', 'CASHOUT', 16.90),
    (3, '2021-10-05', 'CASHIN', 720.90),
    (3, '2021-11-05', 'CASHIN', 720.90),
    (3, '2021-12-05', 'CASHIN', 720.90),
    (4, '2021-10-09', 'CASHBACK', 50.00);

SELECT * FROM CLIENTES;
SELECT * FROM TRANSACOES;

/*
Nível de dificuldade por questão
1 - Fácil
2 - Médio
3 - Difícil
*/

-- QUESTÃO 1 (Fácil) Qual cliente teve o maior saldo médio no mês 11? 
SELECT 
	C.NM_CLIENTE, 
    AVG(T.VR_TRANSACAO) AS SALDO_MEDIO
FROM CLIENTES C
LEFT JOIN TRANSACOES T ON C.CD_CLIENTE = T.CD_CLIENTE
WHERE MONTH(T.DT_TRANSACAO) = 11
GROUP BY C.NM_CLIENTE
ORDER BY SALDO_MEDIO DESC
LIMIT 1;

-- QUESTÃO 2 (Fácil) Qual é o saldo de cada cliente?
SELECT 
	C.NM_CLIENTE, 
    SUM(T.VR_TRANSACAO) AS SALDO_TOTAL
FROM CLIENTES C
LEFT JOIN TRANSACOES T ON C.CD_CLIENTE = T.CD_CLIENTE
GROUP BY C.NM_CLIENTE;

-- QUESTÃO 3 (Médio) Qual é o saldo médio de clientes que receberam CashBack?
WITH CTE_CASHBACK AS (
	SELECT 
		C.NM_CLIENTE, 
        T.VR_TRANSACAO AS VR_TRANSACAO_CASH
	FROM CLIENTES C
	JOIN TRANSACOES T ON C.CD_CLIENTE = T.CD_CLIENTE
	WHERE T.CD_TRANSACAO = "CASHBACK"
    )

SELECT 
	C.NM_CLIENTE, 
    AVG(T.VR_TRANSACAO)
FROM CLIENTES C
LEFT JOIN TRANSACOES t ON c.CD_CLIENTE = t.CD_CLIENTE
INNER JOIN CTE_CASHBACK CASH ON C.NM_CLIENTE = CASH.NM_CLIENTE
GROUP BY C.NM_CLIENTE;

-- QUESTÃO 4 (Difícil) Qual o ticket médio das quatro últimas movimentações dos usuários?
SELECT 
    AVG(T.VR_TRANSACAO) AS TICKET_MEDIO
FROM CLIENTES C
LEFT JOIN (
    SELECT 
        CD_CLIENTE,
        VR_TRANSACAO,
        ROW_NUMBER() OVER (PARTITION BY CD_CLIENTE ORDER BY DT_TRANSACAO DESC) AS RN
    FROM TRANSACOES
) AS T ON C.CD_CLIENTE = T.CD_CLIENTE
WHERE T.RN <= 4;


-- QUESTÃO 5 (Médio) Qual é a proporção entre Cash In/Out mensal?
SELECT 
    YEAR(DT_TRANSACAO) AS ANO,
    MONTH(DT_TRANSACAO) AS MES,
    SUM(CASE WHEN CD_TRANSACAO = 'CASHIN' THEN VR_TRANSACAO ELSE 0 END) AS CASH_IN,
    SUM(CASE WHEN CD_TRANSACAO = 'CASHOUT' THEN VR_TRANSACAO ELSE 0 END) AS CASH_OUT,
    SUM(CASE WHEN CD_TRANSACAO = 'CASHIN' THEN VR_TRANSACAO ELSE 0 END) / SUM(CASE WHEN CD_TRANSACAO = 'CASHOUT' THEN VR_TRANSACAO ELSE 0 END) AS PROPORCAO
FROM TRANSACOES
GROUP BY ANO, MES
ORDER BY MES;

-- QUESTÃO 6 (Difícil) Qual a última transação de cada tipo para cada usuário?
SELECT 
    C.NM_CLIENTE,
    T.CD_TRANSACAO,
    T.DT_TRANSACAO,
    T.VR_TRANSACAO
FROM CLIENTES C
JOIN (
    SELECT 
        CD_CLIENTE,
        CD_TRANSACAO,
        DT_TRANSACAO,
        VR_TRANSACAO,
        ROW_NUMBER() OVER (PARTITION BY CD_CLIENTE, CD_TRANSACAO ORDER BY DT_TRANSACAO DESC) AS RN
    FROM TRANSACOES
) AS T ON C.CD_CLIENTE = T.CD_CLIENTE
WHERE T.RN = 1;

-- QUESTÃO 7 (Médio) Qual a última transação de cada tipo para cada usuário por mês?
SELECT 
    C.NM_CLIENTE,
    T.CD_TRANSACAO,
    T.DT_TRANSACAO,
    T.VR_TRANSACAO
FROM CLIENTES C
LEFT JOIN (
    SELECT 
        CD_CLIENTE,
        CD_TRANSACAO,
        DT_TRANSACAO,
        VR_TRANSACAO,
        ROW_NUMBER() OVER (PARTITION BY CD_CLIENTE, CD_TRANSACAO, YEAR(DT_TRANSACAO), MONTH(DT_TRANSACAO) ORDER BY DT_TRANSACAO DESC) AS RN
    FROM TRANSACOES
) AS T ON C.CD_CLIENTE = T.CD_CLIENTE
WHERE T.RN = 1;

-- QUESTÃO 8 (Fácil) Qual quatidade de usuários que movimentaram a conta?

SELECT COUNT(DISTINCT CD_CLIENTE) AS QUANTIDADE_DE_USUARIOS
FROM TRANSACOES;

-- QUESTÃO 9 (Fácil) (ENTENDI QUE O BALANÇO É CASHIN + CASHBACK - CASHOUT JÁ QUE ESTAMOS FALANDO DO SALDO DO CLIENTE) Qual o balanço do final de 2021?
SELECT 
        YEAR(DT_TRANSACAO),
        SUM(CASE WHEN CD_TRANSACAO = 'CASHIN' THEN VR_TRANSACAO ELSE 0 END) AS CASH_IN,
        SUM(CASE WHEN CD_TRANSACAO = 'CASHOUT' THEN VR_TRANSACAO ELSE 0 END) AS CASH_OUT,
        SUM(CASE WHEN CD_TRANSACAO = 'CASHBACK' THEN VR_TRANSACAO ELSE 0 END) AS CASH_BACK,
        SUM(CASE WHEN CD_TRANSACAO = 'CASHIN' THEN VR_TRANSACAO ELSE 0 END) - SUM(CASE WHEN CD_TRANSACAO = 'CASHOUT' THEN VR_TRANSACAO ELSE 0 END)+ SUM(CASE WHEN CD_TRANSACAO = 'CASHBACK' THEN VR_TRANSACAO ELSE 0 END) AS BALANÇO2021
	FROM CLIENTES C
	JOIN TRANSACOES T ON C.CD_CLIENTE = T.CD_CLIENTE
    GROUP BY YEAR(DT_TRANSACAO);

-- QUESTÃO 10 (Médio) Quantos usuários que receberam CashBack continuaram interagindo com este banco?
SELECT 
	COUNT(DISTINCT C.CD_CLIENTE) AS QUANTIDADE_USUARIOS
FROM CLIENTES C
LEFT JOIN TRANSACOES CB ON C.CD_CLIENTE = CB.CD_CLIENTE AND CB.CD_TRANSACAO = 'CASHBACK'
LEFT JOIN TRANSACOES T ON C.CD_CLIENTE = T.CD_CLIENTE AND T.DT_TRANSACAO > CB.DT_TRANSACAO
WHERE CB.CD_CLIENTE IS NOT NULL
  AND T.CD_CLIENTE IS NOT NULL;
  
-- QUESTÃO 11 (Difícil) Qual a primeira e a última movimentação dos usuários com saldo maior que R$100?
SELECT 
    C.NM_CLIENTE,
    MIN(T.DT_TRANSACAO) AS PRIMEIRA_MOVIMENTACAO,
    MAX(T.DT_TRANSACAO) AS ULTIMA_MOVIMENTACAO
FROM CLIENTES C
JOIN TRANSACOES T ON C.CD_CLIENTE = T.CD_CLIENTE
WHERE T.VR_TRANSACAO > 100
GROUP BY C.NM_CLIENTE;

-- QUESTÃO 12 (Difícil) (ENTENDI QUE O BALANÇO É CASHIN + CASHBACK - CASHOUT JÁ QUE ESTAMOS FALANDO DO SALDO DO CLIENTE) Qual o balanço das últimas quatro movimentações de cada usuário?
SELECT 
    C.NM_CLIENTE,
    SUM(CASE WHEN T.CD_TRANSACAO = 'CASHIN' THEN T.VR_TRANSACAO ELSE 0 END) - SUM(CASE WHEN T.CD_TRANSACAO = 'CASHOUT' THEN T.VR_TRANSACAO ELSE 0 END) + SUM(CASE WHEN T.CD_TRANSACAO = 'CASHBACK' THEN T.VR_TRANSACAO ELSE 0 END) AS BALANCO_ULTIMAS_QUATRO
FROM CLIENTES C
LEFT JOIN (
    SELECT 
        CD_CLIENTE,
        CD_TRANSACAO,
        VR_TRANSACAO,
        ROW_NUMBER() OVER (PARTITION BY CD_CLIENTE ORDER BY DT_TRANSACAO DESC) AS RN
    FROM TRANSACOES
) AS T ON C.CD_CLIENTE = T.CD_CLIENTE
WHERE T.RN <= 4
GROUP BY C.NM_CLIENTE;

-- QUESTÃO 13 (Difícil) Qual o ticket médio das últimas quatro movimentações de cada usuário?
SELECT 
    C.NM_CLIENTE,
    AVG(T.VR_TRANSACAO) AS TICKET_MEDIO
FROM CLIENTES C
LEFT JOIN (
    SELECT 
        CD_CLIENTE,
        VR_TRANSACAO,
        ROW_NUMBER() OVER (PARTITION BY CD_CLIENTE ORDER BY DT_TRANSACAO DESC) AS RN
    FROM TRANSACOES
) AS T ON C.CD_CLIENTE = T.CD_CLIENTE
WHERE T.RN <= 4
GROUP BY C.NM_CLIENTE;